#!/usr/bin/env zsh

pushd $HOME/.dotfiles

echo "stowing nvim"
stow nvim
echo "stowing tmux"
stow tmux
echo "stowing zsh"
stow zsh
echo "stowing ssh"
stow ssh
echo "stowing bin"
stow bin

pushd ./personal_dots
  ./stow
popd
