-- Harpoon
local harpoonUi = require('harpoon.ui')
local harpoonMark = require('harpoon.mark')
vim.keymap.set('n', '<leader>j', function()
    harpoonUi.nav_file(1)
end)
vim.keymap.set('n', '<leader>k', function()
    harpoonUi.nav_file(2)
end)
vim.keymap.set('n', '<leader>l', function()
    harpoonUi.nav_file(3)
end)
vim.keymap.set('n', '<leader>;', function()
    harpoonUi.nav_file(4)
end)
vim.keymap.set('n', '<leader>af', harpoonMark.add_file)
vim.keymap.set('n', '<leader>sf', harpoonUi.toggle_quick_menu)
